name: build 11ty site

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  ELEVENTY_NOTES_PATH_PREFIX: "hypervirtualisation"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies & build
        run: |
          npm install
          npx @11ty/eleventy --pathprefix 'hypervirtualisation'
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'  # Correct path!
          name: github-pages # Good practice

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write # Required for deploying to GitHub Pages with v3
      id-token: write # Required for deploying to GitHub Pages with v3
    steps:
      - id: deployment
        uses: actions/deploy-pages@v3
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}